version: '3'

services: 
  nodejs:
    image: node
    restart: on-failure
    working_dir: /usr/app
    ports: 
      - 8080:8080
    volumes: 
      - .:/usr/app
    command: bash -c "npm install && npm start"